name: template_dart
description: An metaprogramming language for complex class structures in dart
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  meta: '>=1.0.0 < 2.0.0'
  code_builder:
  tuple: 

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
